"""data model

Revision ID: 0002_data_model
Revises: 0001_baseline
Create Date: 2026-06-27 22:32:10.237075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_data_model'
down_revision: Union[str, None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Required by the trigram GIN index on patients.name (partial-name search).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_country', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clinic_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'receptionist', 'doctor', name='member_role'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_members_clinic_id'), 'clinic_members', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_members_user_id'), 'clinic_members', ['user_id'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_user_id'), 'doctors', ['user_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=True),
    sa.Column('phone_national', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_clinic_id'), 'patients', ['clinic_id'], unique=False)
    op.create_index('ix_patients_clinic_phone_national', 'patients', ['clinic_id', 'phone_national'], unique=False)
    op.create_index('ix_patients_name_trgm', 'patients', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rescheduled', 'cancelled', 'no_show', name='appointment_status'), server_default='pending', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_clinic_doctor_start', 'appointments', ['clinic_id', 'doctor_id', 'start_at'], unique=False)
    op.create_index('ix_appointments_patient_start', 'appointments', ['patient_id', 'start_at'], unique=False)
    op.create_table('clinic_doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'doctor_id', name='uq_clinic_doctor')
    )
    op.create_index(op.f('ix_clinic_doctors_clinic_id'), 'clinic_doctors', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinic_doctors_doctor_id'), 'clinic_doctors', ['doctor_id'], unique=False)
    op.create_table('doctor_receptionist_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('receptionist_user_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['receptionist_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_receptionist_grants_clinic_id'), 'doctor_receptionist_grants', ['clinic_id'], unique=False)
    op.create_index('uq_active_grant', 'doctor_receptionist_grants', ['doctor_id', 'receptionist_user_id'], unique=True, postgresql_where='revoked_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_grant', table_name='doctor_receptionist_grants', postgresql_where='revoked_at IS NULL')
    op.drop_index(op.f('ix_doctor_receptionist_grants_clinic_id'), table_name='doctor_receptionist_grants')
    op.drop_table('doctor_receptionist_grants')
    op.drop_index(op.f('ix_clinic_doctors_doctor_id'), table_name='clinic_doctors')
    op.drop_index(op.f('ix_clinic_doctors_clinic_id'), table_name='clinic_doctors')
    op.drop_table('clinic_doctors')
    op.drop_index('ix_appointments_patient_start', table_name='appointments')
    op.drop_index('ix_appointments_clinic_doctor_start', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_patients_name_trgm', table_name='patients', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_patients_clinic_phone_national', table_name='patients')
    op.drop_index(op.f('ix_patients_clinic_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_user_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_clinic_members_user_id'), table_name='clinic_members')
    op.drop_index(op.f('ix_clinic_members_clinic_id'), table_name='clinic_members')
    op.drop_table('clinic_members')
    op.drop_table('users')
    op.drop_table('clinics')
    # The Enum columns auto-created these Postgres types on upgrade; drop_table
    # does not remove the types, so drop them explicitly to keep downgrade clean
    # and re-runnable. (The pg_trgm extension is intentionally left installed —
    # dropping a shared extension on downgrade is risky.)
    sa.Enum(name='appointment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='member_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
